// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM5kyuXjaj5YC2QT3xxeN70V-nUVqRZDo',
    appId: '1:372192224175:web:0d84a8d10f8ed1e7b5c55a',
    messagingSenderId: '372192224175',
    projectId: 'railzo',
    authDomain: 'railzo.firebaseapp.com',
    storageBucket: 'railzo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9jpUbA2gB7SN4elJPD4B8V3rwB4cBVXY',
    appId: '1:372192224175:android:a884a02c8557f7e6b5c55a',
    messagingSenderId: '372192224175',
    projectId: 'railzo',
    storageBucket: 'railzo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClWP3j4SjBaoiMhONNSDhy26OmR4SNjkk',
    appId: '1:372192224175:ios:900f76419450474bb5c55a',
    messagingSenderId: '372192224175',
    projectId: 'railzo',
    storageBucket: 'railzo.firebasestorage.app',
    iosBundleId: 'com.example.railzo',
  );
}
